Dan f97/redux shape
flow-state-15/mod-5-extra-resources pull request #16
Opened 2022-09-13 18:08 UTC by dnlflores

commented out old state shape example for projects students no longer use. Also kept the old generic Soundcloud, and Meetup for later when Airbnb has been fully polished.

2022-09-13 20:06 UTC, alex-pezzati requested changes
This overall looks really great.

I did notice it looked like one or two of the comments look like they were written for the "Beginner" section and then moved into the "Intermediate" section.

Do you think we should have similar comments on the "Beginner" section as well?

2022-09-13 20:06 UTC, alex-pezzati commented on assets/react-redux-state-shape.md
> +        // Notice singleSpot has more data that the allSpots slice. Review your API Docs for more information.
Looks like this comment is meant for the "Beginner" redux state example.

2022-09-14 20:10 UTC, dnlflores commented
I added comments to beginner section for review

2022-09-16 15:49 UTC, alex-pezzati approved these changes
Getting this in for now. We'll make revisions soon.

2022-09-16 15:49 UTC, merged