Whitnessme codesandbox
flow-state-15/mod-5-extra-resources pull request #20
Opened 2022-10-06 23:21 UTC by whitnessme

2022-10-06 23:46 UTC, flow-state-15 commented
@whitnessme Add a line after Table of Contents to remind them to create their own sandbox accounts first, so they don't lose their work. 

We can add a link to this doc under 'Resources' heading [here](https://github.com/flow-state-15/mod-5-extra-resources/tree/main) 

Add a section for opening the built in browser view in a new window so they can use React devTools

2022-10-06 23:46 UTC, flow-state-15 requested changes
check my comments

2022-10-25 23:49 UTC, whitnessme commented
- [x] Add a line after Table of Contents to remind them to create their own sandbox accounts first, so they don't lose their work.
- [x] We can add a link to this doc under 'Resources' heading [here](https://github.com/flow-state-15/mod-5-extra-resources/tree/main)
- [x] Add a section for opening the built in browser view in a new window so they can use React devTools

2022-10-28 21:36 UTC, flow-state-15 approved these changes

2022-10-28 21:36 UTC, merged